FROM datajoint/djbase:py3.9-debian-fcd8909

USER anaconda:anaconda

COPY ./workflow-miniscope/docker/apt_requirements.txt /tmp/
RUN /entrypoint.sh echo "Installed dependencies."

WORKDIR /main

# Option 1 - Install DataJoint's remote fork of the workflow and elements
# RUN git clone https://github.com/datajoint/workflow-miniscope.git /main/

# Option 2 - Install user's remote fork of element and workflow
#            or an unreleased version of the element
# RUN pip install git+https://github.com/<user>/element-lab.git
# RUN pip install git+https://github.com/<user>/element-animal.git
# RUN pip install git+https://github.com/<user>/element-session.git
# RUN pip install "element-interface@git+https://github.com/<user>/element-interface"
# RUN pip install git+https://github.com/<user>/element-miniscope.git
# RUN git clone https://github.com/<user>/workflow-miniscope.git /main/workflow-miniscope

# Option 3 - Install user's local fork of element and workflow
RUN mkdir /main/element-lab \
          /main/element-animal \
          /main/element-session \
          /main/element-interface \
          /main/element-miniscope \
          /main/workflow-miniscope

COPY --chown=anaconda:anaconda ./element-lab /main/element-lab
COPY --chown=anaconda:anaconda ./element-animal /main/element-animal
COPY --chown=anaconda:anaconda ./element-session /main/element-session
COPY --chown=anaconda:anaconda ./element-interface /main/element-interface
COPY --chown=anaconda:anaconda ./element-miniscope /main/element-miniscope
COPY --chown=anaconda:anaconda ./workflow-miniscope /main/workflow-miniscope

RUN pip install -e /main/element-lab
RUN pip install -e /main/element-animal
RUN pip install -e /main/element-session
RUN pip install -e /main/element-interface
RUN pip install -e /main/element-miniscope
RUN rm -f /main/workflow-miniscope/dj_local_conf.json

# Install the workflow
RUN pip install /main/workflow-miniscope
RUN pip install -r /main/workflow-miniscope/requirements_test.txt

WORKDIR /main/workflow-miniscope
