FROM datajoint/djbase:py3.9-debian-8eb1715

ARG GITHUB_USERNAME=datajoint
USER anaconda:anaconda

COPY ./docker/apt_requirements.txt /tmp/
RUN /entrypoint.sh echo "Installed dependencies."

# Install CaImAn
WORKDIR /main
RUN git clone --branch master https://github.com/kabilar/CaImAn
WORKDIR /main/CaImAn
RUN conda install -n base -c conda-forge -y mamba
RUN /bin/bash -c 'mamba env update --n base --file environment-minimal.yml'
RUN pip install .
RUN python caimanmanager.py install --inplace

WORKDIR /main/workflow-miniscope

# 1. Install Elements from github user
RUN pip install --no-deps "element-interface@git+https://github.com/${GITHUB_USERNAME}/element-interface"
RUN pip install --no-deps "djarchive-client@git+https://github.com/${GITHUB_USERNAME}/djarchive-client"
RUN pip install git+https://github.com/${GITHUB_USERNAME}/element-lab.git
RUN pip install git+https://github.com/${GITHUB_USERNAME}/element-animal.git
RUN pip install git+https://github.com/${GITHUB_USERNAME}/element-session.git
RUN pip install git+https://github.com/${GITHUB_USERNAME}/element-event.git
RUN pip install git+https://github.com/${GITHUB_USERNAME}/element-miniscope.git
# RUN pip install git+https://github.com/${GITHUB_USERNAME}/workflow-miniscope.git
# end 1

# 2. Install local fork of element and workflow
# COPY --chown=anaconda:anaconda ../element-lab /main/
# COPY --chown=anaconda:anaconda ../element-animal /main/
# COPY --chown=anaconda:anaconda ../element-session /main/
# COPY --chown=anaconda:anaconda ../element-event /main/
# COPY --chown=anaconda:anaconda ../element-interface /main/
# COPY --chown=anaconda:anaconda ../element-miniscope /main/
COPY --chown=anaconda:anaconda . ./
# RUN pip install -e /main/element-lab
# RUN pip install -e /main/element-animal
# RUN pip install -e /main/element-session
# RUN pip install -e /main/element-event
# RUN pip install -e /main/element-interface
# RUN pip install -e /main/element-miniscope
RUN pip install -e .
# end 2

RUN rm -f ./dj_local_conf.json
RUN pip install -r ./requirements_test.txt
